development:
  adapter: postgresql
  database: template_designer_development
  pool: 5
  timeout: 5000
  username: postgres
  password:

test:
  adapter: postgresql
  database: template_designer_test
  pool: 5
  timeout: 5000
  username: postgres
  password:

production:
  adapter: postgresql
  database: template_designer_production
  pool: 5
  timeout: 5000
